### ISSUE TITLE
Add support for scheduling state machine through cloudwatch

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#10]
Support to trigger the state machine through a scheduled cloudwatch cron

**Comment by ljosyula** [comment]
I'm a GHC 2020 attendee and would like to contribute to this issue. Thanks!

**Comment by monicashete** [comment]
i am ghc 2020 attendee, would like to contribute here

**Comment by RiyaJohn** [comment]
@namitad raised PR for this issue, please take a look at it
