### ISSUE TITLE
Documentation addition for slack_notification support

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#12]
Trapheus readme needs to be enhanced to have details about the support for slack notification for failure alerts

**Comment by ramesht007** [comment]
hey, @namitad can I work on this

**Comment by ramesht007** [comment]
Can we have a discussion and also can you provide me the slack link

**Comment by stationeros** [comment]
PRed and done https://github.com/intuit/Trapheus/pull/41 . Closing this issue.
