### ISSUE TITLE
Optimise AWS permissions for the step function execution

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#121]
The  Lambda execution role has broad permissions here https://github.com/intuit/Trapheus/blob/master/template.yaml#L97 . We should restrict it to the permissions that are required.

**Comment by stationeros** [comment]
Assigned

**Comment by hariingit** [comment]
ManagedPolicyArns:
        - ! Ref AmazonRDSRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AWSStepFunctionsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute

AmazonRDSRolePolicy:
     Type: "AWS::IAM::ManagedPolicy"
     Properties: 
      ManagedPolicyName: !Sub "AmazonrdsRolePolicy"
      Description: "AmazonrdsRolePolicy for AmazonRDSRolePolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Action:   
              application-autoscaling:*
              cloudwatch:*
              "ec2:DescribeAccountAttributes",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeCoipPools",
              "ec2:DescribeInternetGateways",
              "ec2:DescribeLocalGateway:*,
              "ec2:DescribeSecurityGroups",
              "ec2:DescribeSubnets",
              "ec2:DescribeVpcAttribute",
              "ec2:DescribeVpcs",
              "rds:*"
            Effect: "Allow"
            Resource:
              - "*"
          Is this the correct way to do?

**Comment by stationeros** [comment]
You can just check if cloudwatch complete access is required. I don't think you need RDS role policy
