### ISSUE TITLE
Create a jupyter notebook workshop 

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#123]
Create a jupyter notebook for Trapheus that can help show the execution commands in a sandbox environment thus simplifying the installation process currently

**Comment by kokikathir** [comment]
@stationeros I would like to work on this.

**Comment by stationeros** [comment]
Sure , assigned you @kokikathir

**Comment by stationeros** [comment]
@kokikathir  Can you confirm if you are working on this ?

**Comment by kokikathir** [comment]
@stationeros Yes, I m working on this
