### ISSUE TITLE
Fix broken readme links to be compatible with the AWS blog

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#124]
Please ensure your issue adheres to the following guidelines:

- [ ] Use the following format: `* [owner/repo](link)`
- [ ] Link additions should be added to the bottom of the relevant category.
- [ ] New categories or improvements to the existing categorization are welcome.
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order

Thanks for contributing!

As part of the "Getting started with Trapheus" section in AWS blog published on trapheus: https://aws.amazon.com/blogs/opensource/what-is-trapheus/ , there are some links to specific sections of the readme. these links are currently broken in our github repo.

Example: 
<img width="788" alt="Screenshot 2023-09-26 at 4 09 48 PM" src="https://github.com/intuit/Trapheus/assets/23234773/a9922f5a-457b-4ef4-a4d0-d9278a387cee">

Currently, the link in the screenshot above is https://github.com/intuit/Trapheus#pre-requisites and should redirect to the prerequisites section of our readme but the link in github is https://github.com/intuit/Trapheus#-pre-requisites. 

the request is to fix all the github links to ensure the ones mentioned in the blog work as expected.

**Comment by Agnik7** [comment]
Hi! I would like to work on this issue. Requesting the maintainer(s) to assign this issue to me.

**Comment by namitad** [comment]
@Agnik7 have assigned this issue to you.

**Comment by Agnik7** [comment]
Hi @namitad I am a beginner to open source. Could you kindly guide me as to which files need to be changed?

**Comment by namitad** [comment]
@Agnik7 the changes you need to make in the README.md file. the links to different sections of the readme as provided in the above blog are broken. you need to make changes such that links in the readme match the links provided in the blog. 
so you can start with checking what are the links used in the blog (i have provided a sample above) and the cross check in the README.md file to see what changes would be needed in each header for links to match.

**Comment by Agnik7** [comment]
@namitad I have a query. I just checked it, the links in the README.md file are working in the README, but are broken in the aws blog. I don't have an aws account, so I can't edit the blog directly. Is there a way to work around that? I am asking this since the links provided in the README are perfectly valid ones.

**Comment by namitad** [comment]
@Agnik7 The blog cannot be edited. You need to change the links in the github repo so that they match the ones that are in the blog.

**Comment by namitad** [comment]
Basically there were some changes made in the readme post the blog was published which changed the link structure. This resulted in broken links in the blog.

**Comment by Agnik7** [comment]
Ok got it👍

**Comment by Agnik7** [comment]
@namitad I have created a PR #145 to address this issue. Requesting you to kindly review it.
