### ISSUE TITLE
Update reference code structure in readme

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#127]
The code structure reference here: https://github.com/intuit/Trapheus#-contributing-to-trapheus is out dated. 
This issue involves the following fixes:
1. remove the `events` reference
2. add the completed updated structure under the `tests/unit` path
3. add `docs` path
4. add `install.py`, `requirements.txt` and `setup.py`

**Comment by stationeros** [comment]
@Madhura-saw  Assigned you this
