### ISSUE TITLE
Support custom snapshot identifier based db restoration

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#132]
Currently Trapheus supports a limited set of input parameters to the state machine as defined here:  https://github.com/intuit/Trapheus#-execution. The`identifier` parameter refers to the rds instance/cluster id.

The state machine works on the assumption/prerequisite that the restoration will be done using a snapshot with identifier in the format <`identifier`-snapshot> or snapshot creation will create/update snapshot with identifier as <`identifier`-snapshot>.

As part of this issue, we would like to add an enhancement where users can provide a unique `snapshot-identifier` as an additional input parameter to the state machine and the snapshot id provided as a value for this parameter be used for the db restoration process (when `task`=db_restore)

Refer https://github.com/intuit/Trapheus#-execution for more details on `task` types

**Comment by stationeros** [comment]
Can we couple restoration from the identifier as part of this issue as well
