### ISSUE TITLE
Update failure notifications to have details in a structured format

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#141]
Currrently the [email](https://github.com/intuit/Trapheus/blob/master/src/emailalert/email_function.py) and [slack](https://github.com/intuit/Trapheus/blob/master/src/slackNotification/slack_notification.py) notification sent out on pipeline failure contains a text content with the error message as a plain string. 

update both functions to send failure notification in the below format:

```
database id: <identifier name>
snapshot id: <snapshot identifier name>
failed step: <task name>
cause of failure: <error message>
```

**Comment by WallysFerreira** [comment]
I would like to work on this.

**Comment by namitad** [comment]
@WallysFerreira have assigned it to you.

**Comment by WallysFerreira** [comment]
This is my first contribution and I want to make sure I'm on the right track to implement this.

I need to change the expected_message in the 'test_lambda_handler_Error' test to match the new format
then in the lambda_handler I need to get the database id, snapshot id, task name and error message from the event and add it to the message.

Is this right or did I not understand it correctly?

**Comment by namitad** [comment]
@WallysFerreira yes that correct. Please ensure you are making this change for both the email and slack notification lambdas

**Comment by stationeros** [comment]
@namitad  Can we add the executionId from the context object in the email as well, it would help pinpoint the exact execution which failed

**Comment by namitad** [comment]
yes @stationeros that would be good addition and since it might involve changes in the overall state machine, i would prefer to have that as a independent issue.
