### ISSUE TITLE
Support custom snapshot identifier based snapshot creation

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#143]
As part of this issue, we would like to add an enhancement where users can provide a unique snapshot-identifier as an additional input parameter to the state machine and the snapshot id provided as a value for this parameter be used as the id for new snapshot being created (when `task`=create_snapshot or `task`=create_snapshot_only)

Refer https://github.com/intuit/Trapheus#-execution for more details on `task` types

This issue is a **follow up enhancement** to https://github.com/intuit/Trapheus/issues/132 where the input parameter support will be added

**Comment by kokikathir** [comment]
@namitad I would like to work on this

**Comment by namitad** [comment]
@kokikathir this is currently a follow up issue - would you be open to adding the base support for providing a unique `snapshot-identifier` as an additional input parameter to the state machine and use the same as part of the pipeline branching for `task`=create_snapshot or `task`=create_snapshot_only ?

**Comment by kokikathir** [comment]
@namitad Thanks for the clarification. Right now, I'm not focusing on this. You can assign to others
