### ISSUE TITLE
Add an option in TrapheusAI to import a local CSV file 

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#154]
Give an option to user to upload data from a local CSV file and then conduct an analysis using natural language.
https://github.com/intuit/Trapheus/tree/master/labs/TrapheusAI

**Comment by markandey1414** [comment]
Hello @stationeros I would like to work on this issue

**Comment by stationeros** [comment]
Sure @markandey1414 . Assigning this, lets just see how and where can you provide this option in the page though.

**Comment by markandey1414** [comment]
Yes, sure I will look after it. As for the NLP part, I can handle it 👍

**Comment by markandey1414** [comment]
@stationeros just in case, I'm still up for this issue and thanks for assigning me this one :)
will be working today

**Comment by stationeros** [comment]
yes @markandey1414  in case you face any issues , do let us know

**Comment by stationeros** [comment]
@markandey1414  Do let me know , if you are still up for this !!
