### ISSUE TITLE
Add Spanish translation of docs

### ISSUE THREAD

**Issue by virejdasani** [intuit/Trapheus#157]
Please ensure your issue adheres to the following guidelines:

- [x] Use the following format: `* [owner/repo](link)`
- [x] Link additions should be added to the bottom of the relevant category.
- [x] New categories or improvements to the existing categorization are welcome.
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Sort by alphabetical order

Thanks for contributing!

**Comment by stationeros** [comment]
@virejdasani  Closing this due to lack of response. If you are still working , feel free to comment and re-open
