### ISSUE TITLE
[No-Code] Addition of new blogs 

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#159]
* We will accpet the PR as hacktoberfest-accepted for this issue, if the PR adds new blogs in the documentation.
* You can write a blog on [Trapheus](url)/[TrapheusAI](https://github.com/intuit/Trapheus/tree/master/labs/TrapheusAI)  in ,markdown/medium pages . We will update it as Community Spotlight along with your name

**Comment by Rhythm-08** [comment]
I would like to take this issue

**Comment by stationeros** [comment]
@Rhythm-08  Sure, feel free to share the link once ready and we will add your name to the community spotlight

**Comment by Rhythm-08** [comment]
@stationeros Do I need to create a blog and put it inside the docs folder?

**Comment by stationeros** [comment]
You can write and share it as part of this issue

**Comment by SuryaCreatX** [comment]
Can you assign me this issue? Any forward any corresponding details.

**Comment by stationeros** [comment]
Sure Surya,

feel free to publish a blog. If you are more into data/AI/ML , I would
suggest you write about TrapheusAI. You can refer the demo video here
https://medium.com/p/43a4043dc60f

**Comment by shruti-xpg** [comment]
Hi @stationeros ,
Can you assign this  issue to me? would like to contribute.

**Comment by stationeros** [comment]
Hey @shruti-xpg  This is a no-code issue, hence we are not assigning this to anyone, you can contribute a blog in medium and we will update community spotlight and a add a PR with your name so that you can get hacktober credits

@Rhythm-08  @SuryaCreatX  Do let me know if you guys are still working on this.

**Comment by Kundai10** [comment]
@stationeros I have written this article, https://medium.com/@chasindak9/unlocking-the-potential-of-data-with-trapheusai-772d9a1707f1. Let me know if I should rewrite it. I wanted to open a PR with the link to the medium article but there are no clear instructions on how to contribute.
