### ISSUE TITLE
Add tags to generated lambdas

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#163]
The template yaml defines the lambdas that needs to be deployed https://github.com/intuit/Trapheus/blob/master/template.yaml#L182 . We need to add tags as to those lambdas as shown here https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessfunction . 

We can add the tags of ```trapheus-<<functionName>>`` , for instance for ```RenameLambdaFunction```  the corresponding tag would be ```trapheus-rename```

**Comment by sandipnahak** [comment]
@stationeros please assign this to me

**Comment by stationeros** [comment]
@sandipnahak I have merged the PR now. Kindly star us to show some support
