### ISSUE TITLE
Automate installer preferences for Trapheus

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#169]
Currently the installer file for Trapheus https://github.com/intuit/Trapheus/blob/master/install.py asks user for the following 

1. region
2. s3_bucket
3. VPC
4. Subnets
5. notification preferences such as slack webhooks and SES email configs 

The ask is to make the installer more easy, for instance , when the user enters a region, use AWS CLI commands , to get the s3_buckets , VPCs, Subnets etc and present the user an option to pick and choose any or create a new one from the command line itself.

**Comment by srikanth597** [comment]
Hi @stationeros I got the sense of having the implementation for this particular issue, I can probably pick this & work

**Comment by stationeros** [comment]
Thanks @srikanth597  Assigning you this, in case you need any help , feel free to drop a note
