### ISSUE TITLE
Modify Trapheus readme to include TrapheusAI as well 

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#170]
Trapheus now includes another subproject [TrapheusAI](https://github.com/intuit/Trapheus/tree/master/labs/TrapheusAI) . Can we modify the parent readme to include both and clicking of any of them opens up the detailed readme of the required one.

**Comment by avi-dey** [comment]
I am picking this up

**Comment by patHyatt** [comment]
Where should this be grouped under?
![image](https://github.com/intuit/Trapheus/assets/296125/ce7a24c6-6f9d-424d-a079-84a6934e6134)

**Comment by stationeros** [comment]
@patHyatt  The above is the documentation for Trapheus. We need to create a new readme.md files with hyperlinks so that the user can browse which the one they want

**Comment by yash-1o1** [comment]
Can you please assign this to me.

Thank you!

**Comment by stationeros** [comment]
Option two seems fine
