### ISSUE TITLE
Allow the user an option to choose between models for completion API.

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#172]
Have a look at the TrapheusAI demo https://github.com/intuit/Trapheus/tree/master/labs/TrapheusAI#-demo 

We want the user to be given an option to choose between LLM models , which enables them to acquire a type of accuracy and exactness which is beyond just language related stuff.
 
Also the dataset might contain embedded contextual information (schema, short forms) that might not be standardised across the datasets for the same search query, hence might not be well learned by all models.

Hence allowing the users to choose model and iterate on the search. 

https://github.com/intuit/Trapheus/blob/master/labs/TrapheusAI/llm/model.py#L22

**Comment by kshitiz305** [comment]
I would like to contribute to it

**Comment by stationeros** [comment]
@kshitiz305  Assigned you this

**Comment by bazzyadb** [comment]
@stationeros If this issue is not yet resolved, I would like to contribute to this issue.

**Comment by stationeros** [comment]
@kshitiz305  Can you confirm if you are still working on this ?

**Comment by kshitiz305** [comment]
@stationeros Since I am on a new job hunt I was not able to focus on this for a while, let me have a look into this

**Comment by stationeros** [comment]
@bazzyadb  Would you be interested in making some other contribution ?

**Comment by bazzyadb** [comment]
@stationeros I can take https://github.com/intuit/Trapheus/issues/171

**Comment by stationeros** [comment]
Sure

**Comment by kshitiz305** [comment]
Are there any models that need to added beyond gpt-4, gpt-4-0613, gpt-4-32k, gpt-4-32k-0613, gpt-3.5-turbo, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k, gpt-3.5-turbo-16k-0613

**Comment by stationeros** [comment]
For starters we can use gpt-4, gpt-4-32k and gpt-3.5-turbo
