### ISSUE TITLE
Explore the pre version of a major upgrade from open ai

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#173]
Have a look at the TrapheusAI demo https://github.com/intuit/Trapheus/tree/master/labs/TrapheusAI#-demo

OpenAI is prepping up a major version upgrade https://github.com/openai/openai-python#beta-release . We have a dependency on OpenAI https://github.com/intuit/Trapheus/blob/master/labs/TrapheusAI/requirements.txt#L2 for LLMs. 

We can install a pre version of the upgrade by ```pip install --pre openai```

This issue is to explore if anything breaks in TrapheusAI app because of the upgrade post the above installation.

**Comment by hariingit** [comment]
Please assign it to me

**Comment by hariingit** [comment]
@stationeros  https://github.com/intuit/Trapheus/pull/178

**Comment by stationeros** [comment]
Thanks @hariingit  I will test this and get back to you in a day or two

**Comment by stationeros** [comment]
Thanks for contributing this @hariingit . Merged it now, will upgrade and change it to latest in sometime. CTA:- Do star us to show support
