### ISSUE TITLE
Unlimited Load No result 

### ISSUE THREAD

**Issue by kshitiz305** [intuit/Trapheus#185]
Using the current master branch after entering all the details the backend goes into an infinite loop creating multiple requests to the OpenAI and not returning anything.

Here is a video for the same.
https://youtu.be/NSnFOBj5pA8

**Comment by stationeros** [comment]
Thanks for reporting this, will check and revert

**Comment by stationeros** [comment]
@kshitiz305  For the query we are not receiving data from the backend , it didn't go into an infinite loop for me , did you try running with other queries

**Comment by kshitiz305** [comment]
For a same term "sky" how many api hit should it make to the openai API

**Comment by kshitiz305** [comment]
I would love to connect with you to discuss this better. Please do let me know when we can connect and discuss this .

**Comment by stationeros** [comment]
@kshitiz305  Also how are you running the app?

**Comment by kshitiz305** [comment]
The same way as mentioned in the video mentioned above

**Comment by stationeros** [comment]
Can you try a different query instead of sky which returns results?

**Comment by stationeros** [comment]
@kshitiz305  let me know if you are still facing this issue with any query that is returning data
