### ISSUE TITLE
addition of Tags causing deployment failures for trapheus CFT

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#198]
Multiple failures due to addition of tags for resources in template.yaml:
1. securityGroup tag incorrectly added for AWS::Serverless::LayerVersion (tags are not supported for this resource of this type) 
<img width="1665" alt="Screenshot 2023-11-13 at 12 15 28 AM" src="https://github.com/intuit/Trapheus/assets/23234773/a92a0c85-f806-4072-9c05-7c04983845e3">

2. indentation issues which lead to stack creation to be stuck at REVIEW_IN_PROGRESS
     https://github.com/intuit/Trapheus/blob/master/template.yaml#L542
     https://github.com/intuit/Trapheus/blob/master/template.yaml#L569
     https://github.com/intuit/Trapheus/blob/master/template.yaml#L596
     
3. Expected format for Tags is a [list with Key and Value attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-tag.html) which results in deployment errors
<img width="1714" alt="Screenshot 2023-11-13 at 12 22 38 AM" src="https://github.com/intuit/Trapheus/assets/23234773/af7113d6-bfc6-4501-a6e2-1d78efa42add">

**Comment by stationeros** [comment]
Lets check if AWS provides a way to add tags on layers, if not we can remove that altogether
