### ISSUE TITLE
upgrade circle CI to the latest python version

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#201]
Please ensure circle CI is in the latest python version 
https://github.com/intuit/Trapheus/blob/master/.circleci/config.yml#L4

**Comment by HarikaB11** [comment]
Hi @stationeros, I would like to work on this issue.

**Comment by stationeros** [comment]
assigned this to you

**Comment by KhaledAchech** [comment]
Hi @stationeros, is this task still available ?

**Comment by stationeros** [comment]
@KhaledAchech  yes feel free to work on this

**Comment by Zahid07** [comment]
Hi @stationeros If this is open, could you assign this to me

**Comment by stationeros** [comment]
@Zahid07  Feel free to raise a PR, this should be a minor change
