### ISSUE TITLE
Adding code coverage to circle CI and modify the build badge to show the coverage

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#21]
Add code coverage metrics to circle CI and publish it in the build badge.

Refer:- 
https://circleci.com/docs/2.0/code-coverage/#python

**Comment by nachiketdhamankar** [comment]
Hello @stationeros,
I can take this up.

**Comment by sarthakgupta072** [comment]
Hi @stationeros @namitad . I can try taking up this issue.

**Comment by AnshumaJain** [comment]
Hi @namitad, I wanted to take this issue for gracehopperOSD.
