### ISSUE TITLE
"Unresolved resource dependencies [LambdaSecurityGroup]" when UseVPCAndSubnets=false

### ISSUE THREAD

**Issue by SeeleyFamily** [intuit/Trapheus#221]
When running "sam deploy" to create the Trapheus stack, if you specify "UseVPCAndSubnets=false", the creation of the changeset fails due to the following error:
"Status: FAILED. Reason: Template format error: Unresolved resource dependencies [LambdaSecurityGroup] in the Resources block of the template"

To reproduce, simply add UseVPCAndSubnets=false as a parameter.

As a workaround, I can manually edit each lambda and remove each from the VPC after stack creation. However, I wanted to call this to your attention.

Thank you!

**Comment by namitad** [comment]
@SeeleyFamily thank you for reporting this. Will look into a fix at the earliest.
