### ISSUE TITLE
Parallelise the alert and rollback steps in the state machine

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#30]
Presently in the state machine, in any failure scenario, there is an email and optional slack alert configured.
Post the alert, a rollback is initiated. 
Therefore in scenarios of failure in the alert mechanisms, the rollback is also blocked.

https://github.com/intuit/Trapheus/blob/master/screenshots/failure_handling.png

Enhance this sequential part of the state machine such that the alert and rollback happens in parallel.

Resources to start off: https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-parallel-state.html

**Comment by RiyaJohn** [comment]
@namitad I am looking into this issue
