### ISSUE TITLE
Create Definition of Done (DoD) document 

### ISSUE THREAD

**Issue by despot** [intuit/Trapheus#40]
Create a DoD document in .github folder, that will contain all the prerequisites for a feature to be considered Done by the implementer/reviewer. 

Those would entail: 

1. have a UT for the feature covering the happy path and the exception paths, and at least cover 85% of LoC
2. don't have duplicated or redundant code (even in UTs). If the code is duplicated, extract, refactor to get a non-redundant code
3. if you touch a LoC, you are expected to fix or create a UT for it following the above rules (even if this hasn't been followed or was missed by the previous implementer/reviewer)
4. have the appropriate documentation for it in the README file.
5. other?

**Comment by despot** [comment]
@stationeros @namitad @RiyaJohn feel free to discuss amend the feature for the DoD document. I placed some rules which will be beneficial as I see a lot of unclean code or practice for them. 

For instance:  
Points 1. 2. 3. (regarding UTs), the files tests/unit/"mock_....py" are an anti pattern. A lot of the code is copy pasted from the src files - duplicated, redundant and leads to errors.   
Check [test_get_dbstatus_function.py](https://github.com/intuit/Trapheus/pull/34/files#diff-0042cae410c7ace1159ff78b0d262d6b) for the duplication and fix.   
Check [tests/unit/non_mock_common unit tests](https://github.com/intuit/Trapheus/pull/34/files) for a way how you don't have to use those tests/unit/"mock_....py" anti-pattern files.
Point 3. helps with recovering from technical dept, as I see a lot of commits just following the bad practice started by someone else or a miss from someone else.
Point 4. - there are a lot of documentation tickets. These shouldn't exist, as no UT issues should exist. These all should be part of a feature implementation. The development should be done to provide **direct** business value. You might wanna create missed issues like these with something like the lable or prefix [Tech debt], and have these linked to other feature issues that touch the area where the [Tech dept] is, so anyone implementing the feature, would need to fix the tech dept as well. Otherwise you risk, these never to be implemented or to be left as issues but no-one implementing them.
And additionally you should have a process where you would, not only create a [Tech debt] tickets linked it to features, but also notify the implementer/reviewer that created it, with the goal of preventing this in future. 

Feel free to invite others to contribute/discuss the DoD as you see fit.

Cheers

**Comment by stationeros** [comment]
Thanks @despot for this. This looks great - very ambitious but if adhered to will produce an excellent result. I would want  to add the follows. Feel free to comment

Source code for the feature

has been reviewed
is checked in
builds without errors
along with unit tests ( > 85% coverage per PR) is merged upstream in master and branches
which leads to Feature that

passes all integration/functional tests as a gate in PR itself, if not then at least pass through manual testing once.
has been tested and accepted by defined acceptance criteria and test plan
is integrated with install, tear-down or, APIs as appropriate
has documentation for the functionality is available as notes and specs
has no defects which have been introduced
has no performance regression present, if applicable
which ensures that the feature design has been reviewed and agreed upon by the stakeholders and has/in the path of  produced a high quality results

**Comment by stationeros** [comment]
Have incorporated a DoD https://github.com/intuit/Trapheus/blob/master/.github/DEFINITION_OF_DONE.md . Fell free to make further changes there. As such, closing this issue.
