### ISSUE TITLE
Automate further the feature for exporting the snapshot to s3 in a region that doesn't support it.

### ISSUE THREAD

**Issue by despot** [intuit/Trapheus#47]
Depends on:  
- issue-4 "export snapshot to s3 for a region that doesn't support it" case is done ([the PR-34](https://github.com/intuit/Trapheus/pull/34) is accepted)  
- [issue-44](https://github.com/intuit/Trapheus/issues/44) is done

Subtasks:  
1. Implement [a StackSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html) so that you can deploy 2 stacks:  
1.1. the already existing template.yaml/deploy.yaml in the region that doesn't support the export of snapshot to s3 like Frankfurt eu-centra-1). (You might need to link the resources of the template-unsupportedExportOfSnapshotToS3.yaml into the template.yaml.)  
1.2. a new template-unsupportedExportOfSnapshotToS3.yaml, for the region that supports export of snapshot to s3 like Ireland eu-west-1, that will contain:  
1.2.1. the kmskeyid (check the README.md->Pre-requisites for the structure of the copy snapshot kmskey), and   
1.2.2. the bucket:    
  SnapshotsBucket:  
    Type: AWS::S3::Bucket  
    Condition: HasExportSnapshotSupportedRegion  
    Properties:  
      BucketName: !Join [ "", [ !Sub "rds-snapshots-${AWS::AccountId}-",!Ref ExportSnapshotSupportedRegion ] ]  
1.2.3. and any other region resources that are required to.   
(You can't specify the other region resources in the same template.yaml, hence a new template-unsupportedExportOfSnapshotToS3.yaml is required)  
2. Modify the E2E test to run without the steps for manually setting kmskey kmskeyid and bucket in the export supporting region (in other words you would not need to do [point 2.3. from issue-44](https://github.com/intuit/Trapheus/issues/44)). 

Goal: Reduce the time the user takes to provide manual inputs in order to have a snapshot exported to s3 for a region that doesn't support it.

**Comment by despot** [comment]
You should end up with the state machine green path from the attached image. 
![exportSnapshotToS3ForARegionThatDoesntSupportIt_useCase](https://user-images.githubusercontent.com/1583742/96444553-bb879880-120e-11eb-8907-315e3cf3968d.jpg)

**Comment by stationeros** [comment]
Added the support. Closing this issue.
