### ISSUE TITLE
[Testing] refactor test files to improve code quality and coverage

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#54]
Please ensure your issue adheres to the following guidelines:

Refactor the tests files to remove code duplication of the common src utility files in the test folder (ex: mock_utility, mock_constants). 
Make use of patch to efficiently access and mock the utility files within the tests as well.

- [ ] Use the following format: `* [owner/repo](link)`
- [ ] Link additions should be added to the bottom of the relevant category.
- [ ] New categories or improvements to the existing categorization are welcome.
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] Sort by alphabetical order

Thanks for contributing!

**Comment by stationeros** [comment]
@namitad Thanks for contributing. Hoping to see more encore contributions in the future.
