### ISSUE TITLE
Separate create_snapshot from db_restore so latter is not run automatically

### ISSUE THREAD

**Issue by freyp577** [intuit/Trapheus#63]
Hi, I have an enhancement request for Trapheus
we would like to use Trapheus to create and export a Snapshot from one AWS Environment
transfer the exported snapshot to a target Environment (different account) and then restore the snapshot there

currently task create_snapshot does automatically and always run into the db_restore part.
To achieve what we need there need to be a way to separate create_snapshot task from db_restore, so db_restore not to be run after successful create_snapshot

maybe there are various ways to do that, but the simplest one would to do a small (one liner) modification to template.yaml to the step function 

```
"StartClusterSnapshotExportTask": {
                "Type": "Task",
                "Resource": "${ClusterSnapshotExportLambdaArn}",
                "Next": "ClusterRename",
```

by changing ClusterRename to RestorePipelineComplete

We would like to use the code as is so not to clone your code but would like to see this in there.
Or maybe introduce a task create_shapshot_only Task / action and extend the decision logic to stop the step function after having exported the RDS snapshot to S3?

Please feedback on whether such a modification would be possible.
Regards, Peter

**Comment by namitad** [comment]
Hi @freyp577, great to hear that you and your team have found Trapheus quite handy. 
Considering your request and the present support in the pipeline, i would be more inclined towards introducing the new branch of "update_snapshot_only" as it will not break the existing functionality and various branches while also adding a support for snapshots individually. 
do let us know about your thoughts on the same and if you would like to contribute this capability to trapheus.

**Comment by freyp577** [comment]
Having the changes in a branch would be ok to us. Our concern is that if we modify the existing code, we may run on long terms into troubles having to maintain it in-house, what we would like to prevent

Also not, it is not my main concern, as I am developer and feel comfortable also to change things, when there is time for that, ... but it is more a request from the maintenance team that is involved here

so if there is a branch and the perspective that it may or will slip into the master branch (sooner or later) than it is ok to us.

**Comment by freyp577** [comment]
and about contributing: you mean that I provide this branch and submit it as merge request?

**Comment by namitad** [comment]
@freyp577 for branching - within the pipeline, what can be done is add a `update_snapshot_only` option in addition to the existing `create_snapshot` and `db_restore` branches which can do the tasks of just updating the snapshot and exporting. 

Do let us know if you would like to contribute this enhancement to the project as a PR.

**Comment by RiyaJohn** [comment]
@namitad From the simple solution that @freyp577 suggested, how about having update_snapshot_only as an input parameter that user passes and accordingly we can modify the template to decide if statemachine step has to stop after create and export or should continue to restore. I can work on this if this sounds good
