### ISSUE TITLE
[Core] Add support having the snapshot id as an input to the state machine

### ISSUE THREAD

**Issue by namitad** [intuit/Trapheus#8]
Presently in the state machine, by default the snapshot identifier is expected to be of the format db-instance-identifier-snapshot.

As an enhancement, enable users to provide the snapshot id as part of the inputs to the state machine, not having to adhere to the default format as above. Also modify the lambdas to support reading of input across the various steps in the state machine.

**Comment by stationeros** [comment]
Closing this issue, I will pick it up with Eventing later
