### ISSUE TITLE
Fix broken link for AWS VPC documentation

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#97]
The following link in the documentation is no longer maintained. Find an alternative for this.

<img width="793" alt="Screenshot 2023-08-23 at 9 49 14 AM" src="https://github.com/intuit/Trapheus/assets/112308320/d5b6efe9-5ba2-4401-b025-30b4ee0be47b">

**Comment by kshitiz305** [comment]
https://docs.aws.amazon.com/quickstart/latest/vpc/welcome.html

Page doesn't seem to be broken

**Comment by stationeros** [comment]
the page insn't maintained or supported, we can possiblt link to the VPC quickstart guide https://aws-quickstart.github.io/quickstart-aws-vpc/ since this part talks about a minimal VPC setup

**Comment by kshitiz305** [comment]
HI @stationeros I would like to bring it to your notice that I am looking for an opportunity and would like to connect with regarding the same to discuss if you have an opening in your company and if it might suit my profile.

**Comment by stationeros** [comment]
You can check our careers page for a job that matches your requirements. I would be more than happy to drop in a referral. Feel free to reach out to me at rite2rohit88@gmail.com
